<!--
2026-05-19 (Luiz/dev): PLAN.md.tpl — template do populate-harness.
Decisao: D1 e D4 do PRD populate-plan-andre-port (MH-2 / CA-03).
Fonte canonica das 10 primeiras secoes: skills/lib/exec-plan-sections.ts (EXEC_PLAN_SECTIONS_FULL).
11a secao (Observability) e melhoria nossa: descreve audit log do Step 91.
3 opcionais (Follow-up Plans, Final Report, Pre-GO) entram como comentario — CA-03 do PRD diz
"ausentes ou marcadas". NUNCA promover a H2 sem conteudo real.

Variaveis interpoladas pelo renderer (populate-plan-generator.ts, applyVars):
  {{PROJECT_NAME}}  — nome do projeto (frontmatter + heading)
  {{DATE}}          — YYYY-MM-DD da geracao
  {{PHASES_TABLE}}  — bloco Markdown ja renderizado com tabela de fases

Para escapar literais `{{` `}}` no corpo, evitar — applyVars usa replaceAll sem regex,
entao apenas as chaves declaradas acima sao substituidas.
-->
---
title: "Populate Harness — {{PROJECT_NAME}}"
mode: populate-harness
status: active
created: {{DATE}}
project: {{PROJECT_NAME}}
---

# Plan: Populate Harness — {{PROJECT_NAME}}

**Generated by:** /anti-vibe-coding:init (Step 91-generate-populate-plan)
**Date:** {{DATE}}
**Status:** active

---

## Goal

Popular todos os docs canonicos do projeto `{{PROJECT_NAME}}` com conteudo real extraido do
codebase — zero placeholder, cada afirmacao referencia um arquivo lido. O contrato Harness
do Andre exige docs vivos, nao templates genericos.

## Scope

**In scope:**
- Popular cada doc canonico listado em `Execution Steps` (1 fase por doc).
- Subagente `harness-populator` consome inputs declarados (docs candidatos + paths de codigo).
- Validacao por leitura humana via PR review.

**Out of scope:**
- COMPOUND_ENGINEERING.md (meta-doc filosofico — D5 do PRD exclui).
- Geracao de testes de codigo (responsabilidade de outros planos).
- Refactor do codigo lido (somente leitura).

## Assumptions

- Stack ja detectado por Step 03 (`detect-stack-and-register`).
- `discovery-manifest-light` ja capturou docs existentes (Step 06 ou greenfield = vazio).
- `stack-aware-input-paths` ja mapeou paths reais por doc canonico (Step 12 ou fallback).
- Subagente populator tem acesso de leitura ao repo.

## Risks

- Doc orfao sem destino canonico obvio (DQ2 do CONTEXT) — subagente marca `needsUser`.
- Path em `Inputs (codigo)` pode estar marcado como `nao encontrado` (movido/renomeado) — verificar antes de citar.
- Conteudo gerado pode duplicar info entre docs (ex: ARCHITECTURE vs DESIGN) — humano consolida no PR.

## Execution Steps

{{PHASES_TABLE}}

## Review Checklist

- [ ] Cada doc populado tem ZERO placeholder generico (`TBD`, `lorem`, `<descricao>`).
- [ ] Cada afirmacao no doc referencia path real do repo (verificavel com `grep`).
- [ ] Itens marcados `needsUser` foram resolvidos no PR ou registrados em `MEMORY.md`.

## Validation Log

<!-- preencher durante /execute-plan: comando + resultado por fase -->

## Compound Opportunity

<!-- preencher ao /iterate: o que merece virar compound note? Ex: padroes recorrentes entre docs, gotchas de subagente, ajustes de heuristica candidate-docs. -->

## Lessons Captured

<!-- preencher ao /iterate: links para docs/compound/*.md gerados a partir desta execucao. -->

## Exit Criteria

- [ ] Todos os docs canonicos populados (= numero de fases mergeadas no PR).
- [ ] `bun run test` e `bun run lint` verdes apos PR.
- [ ] Humano aprovou via PR review — sem comentarios de placeholder pendente.

## Observability

Step 91 emite audit log estruturado por execucao com os seguintes campos:

- `subagent_id`: id do subagente populator que rodou cada fase.
- `input_paths`: lista de paths lidos (docs candidatos + codigo) — auditavel.
- `contagens`: numero de inputs por doc canonico, numero de outputs gerados, numero de
  `needsUser` emitidos.
- `duracao_ms`: tempo total da fase.

Audit log e persistido em `docs/exec-plans/active/{{DATE}}-populate-harness/audit.log.jsonl`
(append por fase). Plano 05 fase-02 detalha o contrato.

<!-- opcional: Follow-up Plans — preencher quando outros planos dependerem deste populate-harness (ex: plano de refactor que precisa dos docs como input). -->

<!-- opcional: Final Report — preencher ao fechar o PR com metricas (numero de docs populados, retries, tempo total). -->

<!-- opcional: Pre-GO decisoes pendentes — preencher se houver decisoes que ainda precisam de aprovacao humana antes do merge. -->
