import { promises as fs } from 'node:fs'
import path from 'node:path'
import { detectInitMode } from './migration-mode-detector'
import type { InitMode } from './migration-mode-detector'

export type MigrationTracerResult =
  | {
      status: 'ok'
      planPath: string
      manifestPath: string
      detectedMode: 'migration'
    }
  | {
      status: 'wrong-mode'
      detectedMode: InitMode
      planPath: null
      manifestPath: null
    }
  | {
      status: 'error'
      error: string
      planPath: null
      manifestPath: null
    }

function buildMigrationPlanContent(projectName: string, docCount: number, date: string): string {
  return `# Migration Plan: ${projectName} → Anti-Vibe Coding

## Goal

Map existing institutional documentation (${docCount} files detected in docs/) to the
Anti-Vibe Coding harness structure (22 André Prado canon files + 4 anti-vibe extensions).
Each mapped file becomes a migration task in Execution Steps.

## Scope

- In scope: all .md files in docs/ and root not generated by the harness scaffold
- Out of scope: source code files, .env, secrets, binaries, node_modules

## Assumptions

- Existing docs contain institutional knowledge worth preserving (not auto-generated)
- No Anti-Vibe Coding harness is currently installed in this project
- Operator will review each migration step before executing

## Risks

- Existing docs may partially overlap with canon files (conflict resolution needed per file)
- Some docs may have no direct mapping to canon — will be placed in docs/design-docs/ as ADRs
- Migration is additive: existing files are not deleted, harness files are added alongside

## Execution Steps

1. Run \`/anti-vibe-coding:init\` with migration pipeline (Phases 1-3 via subagents) to generate
   per-file migration plans — or execute manually following the steps below.
2. For each file in docs/ that maps to a canon slot: review overlap, merge content, write to
   the canon destination (e.g., docs/DESIGN.md, docs/SECURITY.md).
3. For each file with no canon mapping: create ADR in docs/design-docs/ADR-NNNN-{slug}.md
   preserving the original content under Context/Decision/Consequences sections.
4. Install Anti-Vibe Coding harness: run \`/anti-vibe-coding:init --force-migration-complete\`
   to scaffold remaining canon files (empty templates for unmapped slots).
5. Run \`bun run harness:validate\` to confirm all required canon files are present.
6. Update \`.claude/.anti-vibe-manifest.json\` to flip \`initMode\` from "migration" to "completed".

## Review Checklist

- [ ] All existing docs reviewed against the 22 canon-andre slots
- [ ] All existing docs reviewed against the 4 anti-vibe-extension slots
- [ ] Files with overlap documented (merge strategy per file)
- [ ] Files with no mapping converted to ADRs (docs/design-docs/)
- [ ] \`bun run harness:validate\` passes after migration

## Validation Log

- [ ] Detection: \`migration-mode-detector.ts\` reported ${docCount} non-harness docs in docs/
- [ ] Tracer Bullet: this file generated by \`runMigrationTracer\` on ${date}
- [ ] Subagent phases: pending (Planos 02/03 — blocked on v6.1.0)

## Compound Opportunity

Review each existing doc for durable lessons worth capturing in docs/compound/*.md
after migration completes. The migration process itself may reveal project-specific
gotchas about the existing architecture — capture those as compound notes.

## Lessons Captured

- Migration mode detected and tracer bullet executed successfully
- 10-section shape validated against new-plan.ts template (André Prado canon)

## Exit Criteria

- \`bun run harness:validate\` returns exit 0
- \`.claude/.anti-vibe-manifest.json\` has \`initMode: "completed"\`
- All pre-existing docs either merged into canon slots or converted to ADRs
`
}

export async function runMigrationTracer(targetDir: string): Promise<MigrationTracerResult> {
  const { mode, signals } = await detectInitMode(targetDir)
  if (mode !== 'migration') {
    return { status: 'wrong-mode', detectedMode: mode, planPath: null, manifestPath: null }
  }

  const docCountSignal = signals.find((s) => s.type === 'populated-docs')
  const docCount = docCountSignal?.count ?? 0

  const projectName = path.basename(targetDir)

  const activePlansDir = path.join(targetDir, 'docs', 'exec-plans', 'active')
  await fs.mkdir(activePlansDir, { recursive: true })

  const date = new Date().toISOString().slice(0, 10)
  const slug = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
  const planFileName = `${date}-migration-plan-${slug}.md`
  const planPath = path.join(activePlansDir, planFileName)

  const planContent = buildMigrationPlanContent(projectName, docCount, date)
  await fs.writeFile(planPath, planContent, { encoding: 'utf8', flag: 'wx' }).catch(
    async (err: unknown) => {
      if (err instanceof Error && 'code' in err && (err as { code: string }).code === 'EEXIST') {
        await fs.writeFile(planPath, planContent, 'utf8')
      } else {
        throw err
      }
    },
  )

  const claudeDir = path.join(targetDir, '.claude')
  await fs.mkdir(claudeDir, { recursive: true })

  const manifestPath = path.join(claudeDir, '.anti-vibe-manifest.json')
  const manifest = {
    initMode: 'migration' as const,
    installedAt: new Date().toISOString(),
    tracerBullet: true,
    migrationPlan: path.relative(targetDir, planPath).replace(/\\/g, '/'),
    detectedDocCount: docCount,
  }
  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8')

  return { status: 'ok', planPath, manifestPath, detectedMode: 'migration' }
}
