// skills/init/lib/populate-harness-prd-template.ts
// 2026-05-21 (Luiz/dev): Plano 02 fase-01 — PRD da pasta populate-harness.

export type PRDInput = {
  readonly dateSlug: string
  readonly stackPrimary: string
  readonly legacyArtifactsFound: number
}

export function renderPopulateHarnessPRD(input: PRDInput): string {
  return [
    '---',
    `slug: populate-harness`,
    `date: ${input.dateSlug}`,
    `status: ready`,
    '---',
    '',
    '# PRD: Populate Harness',
    '',
    '**Generated by:** /anti-vibe-coding:init (Step 7 — generate-populate-plans)',
    `**Stack detected:** ${input.stackPrimary}`,
    `**Legacy artifacts found:** ${input.legacyArtifactsFound}`,
    '',
    '## Problema',
    '',
    'O harness do Anti-Vibe Coding tem 16 documentos canonicos que precisam de',
    'conteudo real extraido deste repositorio. Sem essa etapa, os arquivos ficam',
    'como templates genericos e a LLM nao consegue dar conselho ancorado no projeto.',
    '',
    '## Outcome',
    '',
    'Os 16 docs canonicos populados com conteudo derivado do codigo real, validados',
    'por `bun run harness:validate`, com zero placeholders restantes.',
    '',
    '## Escopo',
    '',
    'Cada uma das 16 fases (`fase-NN-*.md`) trata de UM doc canonico. Sao paralelizaveis',
    'na Wave 1 (Discovery), mas a Wave 2 (Write sections) de cada fase respeita as',
    'dependencias declaradas em `dependsOn` da respectiva fase.',
    '',
    '## Referencia',
    '',
    '- ADR-0022 (`docs/design-docs/ADR-0022-faseplan-schema-andre-parity.md`)',
    '- Schema `FasePlanInput v1` em `skills/init/lib/render-fase-plan.ts`',
    '',
  ].join('\n')
}
