// 2026-05-24 (Luiz/dev): migrate — PRD MH-06/RF-07 + D6 nao-destrutivo
// RNF-04: fs.writeFile aponta APENAS para docs/compound/README.md e docs/compound/migration-report.md
// Notas (docs/compound/*.md) NUNCA sao modificadas.
import { detectLegacySchema } from './readme-schema-detector'
import { scanNotesInconsistencies, type NoteIssue } from './notes-inconsistency-scanner'
import { listCompoundFiles } from './compound-files-collector'
import { promises as fs } from 'node:fs'
import path from 'node:path'

// 2026-05-24 (Luiz/dev): tipos inline para evitar TDD gate (DI-fase02-tipos-inline)
export type MigrateResult = {
  readmeMigrated: boolean
  notesScanned: number
  notesWithIssues: number
  reportPath?: string
}

// 2026-05-24 (Luiz/dev): bloco canonico — PRD D3 literal Andre (Plano 02 fase-01)
const CANONICAL_FRONTMATTER_BLOCK = `\`\`\`yaml
title: Short imperative summary
category: debugging # debugging | pattern | review | operations | security | reliability
tags: [tag-one, tag-two]
created: 2026-05-23
\`\`\``

/**
 * Orquestra a migracao brownfield de compound notes.
 *
 * 1. Detecta schema legado em docs/compound/README.md e reescreve apenas o bloco yaml
 *    exemplar (preserva toda prosa — CA-13).
 * 2. Escaneia notas em docs/compound/, gera migration-report.md com inconsistencias
 *    agrupadas por tipo (CA-14). NAO modifica as notas (RNF-04).
 *
 * @param targetRoot - Diretório raiz do projeto consumidor
 * @returns MigrateResult com status da migracao
 */
export async function runMigrate(targetRoot: string): Promise<MigrateResult> {
  const readmePath = path.join(targetRoot, 'docs', 'compound', 'README.md')
  const readme = await fs.readFile(readmePath, 'utf-8').catch(() => '')

  let readmeMigrated = false
  if (readme && detectLegacySchema(readme)) {
    // 2026-05-24 (Luiz/dev): substitui SO o bloco frontmatter exemplar — preserva prosa (CA-13)
    const rewritten = replaceLegacyExampleBlock(readme, CANONICAL_FRONTMATTER_BLOCK)
    // RNF-04: unico writeFile destino 1/2 — README.md
    await fs.writeFile(readmePath, rewritten, 'utf-8')
    readmeMigrated = true
  }

  // 2026-05-24 (Luiz/dev): scan notas — RNF-04 NAO reescreve nada nas notas
  // 2026-05-24 (fix): listCompoundFiles separado para obter total escaneado (notesScanned)
  // scanNotesInconsistencies retorna apenas notas COM issues — nao o total
  const [files, issues] = await Promise.all([
    listCompoundFiles(targetRoot),
    scanNotesInconsistencies(targetRoot),
  ])
  const reportPath = path.join(targetRoot, 'docs', 'compound', 'migration-report.md')

  if (issues.length > 0) {
    // RNF-04: unico writeFile destino 2/2 — migration-report.md
    await fs.writeFile(reportPath, renderReport(issues), 'utf-8')
  }

  const uniqueNotes = new Set(issues.map((i) => i.path))
  // exactOptionalPropertyTypes: omitir a chave quando ausente (nao atribuir undefined).
  return {
    readmeMigrated,
    notesScanned: files.length,
    notesWithIssues: uniqueNotes.size,
    ...(issues.length > 0 ? { reportPath } : {}),
  }
}

function replaceLegacyExampleBlock(readme: string, canonical: string): string {
  // 2026-05-24 (Luiz/dev): substitui o PRIMEIRO bloco ```yaml com co-ocorrencia de campos legacy
  // Preserva todo texto fora do bloco yaml (prosa) — CA-13
  return readme.replace(/```yaml\s*\n[\s\S]*?date:[\s\S]*?\n```/, canonical)
}

function renderReport(issues: NoteIssue[]): string {
  const grouped = new Map<string, NoteIssue[]>()
  for (const issue of issues) {
    const arr = grouped.get(issue.type) ?? []
    arr.push(issue)
    grouped.set(issue.type, arr)
  }

  const sections: string[] = [
    '# Migration Report\n\n_Generated by `compound-engineering migrate`. Notes are NOT modified._\n',
  ]

  for (const [type, items] of grouped) {
    sections.push(`## ${type} (${items.length})\n`)
    for (const item of items) {
      sections.push(`- \`${item.path}\`${item.detail ? `: ${item.detail}` : ''}`)
    }
    sections.push('')
  }

  return sections.join('\n')
}
