#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    # Anti-Vibe fix (2026-08-12): explorer.exe exits 1 even when it opened the browser —
    # measured on Windows 11 / Git Bash. Without `|| true` the group below fails and every
    # successful open prints "couldn't open a browser". Do not remove: the exception is
    # explorer.exe-specific on purpose, so the other branches keep their real warning.
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url" || true
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  # Anti-Vibe fix (2026-08-12): drop a trailing CR before the value propagates.
  # On a CRLF .env under POSIX, `line` arrives as `KEY=value<CR>` and that CR rides
  # into write_env and set_secret — a GitHub secret with an invisible CR only fails
  # at CI runtime. Normalising on read, not on write: write_env must not rewrite
  # lines this wizard never touched. Keep this even though Git Bash masks the bug
  # (MSYS2 strips the CR in grep, in tail, and in command substitution).
  line="${line%$'\r'}"
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Security tooling — ZAP baseline + Trivy (limpeza final do shift-left).
#
# Instala os dois workflows no projeto e captura o que so o humano pode dar: a
# AUTORIZACAO do alvo do scan, a credencial do registry, e o toggle de Code
# Scanning no painel do GitHub. Procedimento, limites e quando apertar o gate:
# skills/security/references/ci-security-tooling.md
#
# Rode a partir da RAIZ do projeto alvo:
#   bash /caminho/do/plugin/scripts/security-tooling-wizard.sh

TOTAL_STAGES=4

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOW_SRC="$PLUGIN_ROOT/skills/init/assets/static/.github/workflows"
TARGET_DIR="$PWD"

banner "Security tooling — ZAP baseline + Trivy"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Autorizar o alvo do ZAP"
say "O ZAP so pode escanear host que voce tem autorizacao para escanear."
say "O passe local do /verify-work aceita apenas localhost; em CI o alvo e externo,"
say "entao esta resposta sua E a autorizacao — nao existe allowlist para cair atras."
note "Escanear host de terceiro sem autorizacao e ilegal em varias jurisdicoes."
printf '\n'
if confirm "Voce tem autorizacao para escanear o ambiente que vai informar?"; then
  ask ZAP_TARGET_URL "URL do staging/preview (ex: https://staging.suaapp.com):"
  case "${ZAP_TARGET_URL:-}" in
    https://*|http://*)
      write_env ZAP_TARGET_URL "$ZAP_TARGET_URL"
      set_var   ZAP_TARGET_URL "$ZAP_TARGET_URL"
      ;;
    "")
      warn "sem URL — o ZAP fica instalado, mas o job falha ate a variavel existir"
      SKIPPED+=("variavel ZAP_TARGET_URL")
      ;;
    *)
      warn "a URL precisa comecar com http:// ou https:// — nada gravado"
      SKIPPED+=("variavel ZAP_TARGET_URL (valor informado era invalido)")
      ;;
  esac
else
  say "Sem problema. O ZAP fica instalado e inerte; o Trivy nao depende disto."
  SKIPPED+=("variavel ZAP_TARGET_URL (autorizacao nao confirmada)")
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Imagem de container para o Trivy (opcional)"
say "O scan de IaC roda em qualquer projeto e nao precisa de configuracao nenhuma."
say "O scan de imagem so liga se voce publicar uma — a maioria dos projetos nao publica."
printf '\n'
if confirm "Este projeto publica uma imagem de container?"; then
  ask TRIVY_IMAGE_REF "Referencia da imagem (ex: ghcr.io/org/app:latest):"
  if [[ -n "${TRIVY_IMAGE_REF:-}" ]]; then
    write_env TRIVY_IMAGE_REF "$TRIVY_IMAGE_REF"
    set_var   TRIVY_IMAGE_REF "$TRIVY_IMAGE_REF"
    printf '\n'
    if confirm "O registry e privado (precisa de credencial para puxar a imagem)?"; then
      ask        REGISTRY_USERNAME "Usuario do registry:"
      ask_secret REGISTRY_TOKEN    "Token do registry:"
      set_secret REGISTRY_USERNAME "$REGISTRY_USERNAME"
      set_secret REGISTRY_TOKEN    "$REGISTRY_TOKEN"
      note "Ressalva da doc do Trivy: essa credencial vale para TODO registry que o scan"
      note "encontrar, nao so o seu. Se a imagem puxar camada de outro registry, ela vai junto."
    fi
  else
    warn "sem referencia — o job de imagem continua pulado"
  fi
else
  say "Ok. O job de imagem fica pulado por 'if: vars.TRIVY_IMAGE_REF != \"\"'."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Ligar o Code Scanning"
say "O Trivy manda o resultado em SARIF para a aba Security. Sem Code Scanning ligado,"
say "o upload nao vira alerta visivel — e o achado se perde em silencio."
printf '\n'
REPO_SLUG=""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  REPO_SLUG=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)
fi
if [[ -n "$REPO_SLUG" ]]; then
  open_url "https://github.com/$REPO_SLUG/settings/security_analysis"
else
  note "Nao consegui descobrir o repo pelo gh — abra voce: Settings do repo, secao de"
  note "seguranca (o nome varia: 'Advanced Security' ou 'Code security and analysis')."
fi
step "Procure a entrada de Code scanning e habilite."
note "O GitHub renomeia e move esse painel de tempos em tempos, e ele difere entre plano"
note "gratuito, Team e Enterprise. Se o rotulo nao bater com o que descrevi, procure na"
note "pagina por 'Code scanning' — nao vou fingir que sei a tela exata da sua conta."
note "Repo privado sem Advanced Security nao tem a opcao: nesse caso troque exit-code para"
note "'1' no trivy.yml, para o achado travar o job em vez de virar alerta que ninguem ve."
pause "Feito? Enter para continuar."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Instalar os workflows no projeto"
say "Destino: $TARGET_DIR"
say "Origem:  $WORKFLOW_SRC"
printf '\n'
if [[ "$TARGET_DIR" == "$PLUGIN_ROOT" ]]; then
  warn "voce esta rodando dentro do proprio plugin, nao num projeto alvo."
  warn "Este repo nao tem app HTTP, imagem nem IaC — nao ha o que escanear aqui."
  SKIPPED+=("copia dos workflows (rode a partir da raiz do projeto alvo)")
elif [[ ! -d "$WORKFLOW_SRC" ]]; then
  warn "nao encontrei os templates em $WORKFLOW_SRC"
  SKIPPED+=("copia dos workflows (caminho do plugin nao resolveu)")
else
  mkdir -p "$TARGET_DIR/.github/workflows"
  for wf in zap-baseline.yml trivy.yml; do
    dst="$TARGET_DIR/.github/workflows/$wf"
    if [[ -f "$dst" ]] && ! confirm "$wf ja existe — sobrescrever?"; then
      SKIPPED+=(".github/workflows/$wf (mantido o arquivo existente)")
      continue
    fi
    cp "$WORKFLOW_SRC/$wf" "$dst"
    printf '  %s✓ instalado%s .github/workflows/%s\n' "$GREEN" "$RESET" "$wf"
  done
fi
printf '\n'
note "Os dois nascem reportando, nao bloqueando. Quando e por que apertar o gate:"
note "  skills/security/references/ci-security-tooling.md"

finish
